### ISSUE TITLE
USER STORY: Provide anonomous feedback

### ISSUE THREAD

**Issue by kerrie-jones** [kerrie-jones/First-Agile-Project#4]
In order to **provide anonomous feedback** as a **user**, I can **choose to hide my identity in the poll response**.
## Acceptance Criteria
- Option should be provided as a checkbox
- The Checkbox should be checked by default
- The option should appear next to the submit button
## Tasks
- [ ] Update the view: the poll design (HTML and CSS) to include checkbox and to show the name of the submittor
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
